name: DockerFile

on:
  push:
    branches: [ "feature-dockerfile" ]
  workflow_dispatch:
permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  build_and_scan:
    name: Build, Scan, and Push Docker Image
    runs-on: ubuntu-20.04
    env:
      AppName: 'spring-petclinic'
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
        
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/sachinmaniyar/spring-petclinic:11.0 .
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CR_Username }}
          #username: ${{ github.actor }}
          password: ${{ secrets.CR_Password }}
          #password: ${{secrets.GH_TOKEN}}
          registry: ghcr.io
          
      - name: Push Docker Image
        run: |
          docker push ghcr.io/sachinmaniyar/${{ vars.IMG_NAME }}:11.0
